### ISSUE TITLE
Readme: Hello, Golioth Produces an Error

### ISSUE THREAD

**Issue by keenanjohnson** [golioth/golioth-esp-idf-sdk#69]
### ESP-IDF version

4.4.1

### Golioth ESP-IDF SDK Commit Hash

07a169d67af8cc6d05b7d21773ec681115e78325

### Hardware Target

esp32s3

### What host OS are you using?

Osx 13

### Current Behavior

The Readme describes what is a minimum example for golioth to run. However, this code when run produces an error stating that nvs must be initialized.

To fix this, I believe the call to initiatlize nvs must be added to the readme minimum example.

### Steps To Reproduce

Copy the readme minimum example into a project, build, flash, and monitor.

**Comment by ncmiller** [comment]
Thanks for reporting this @keenanjohnson 

I'll update the sample code with this change, and check for anything else that might be missing to get it to compile and run.
