### ISSUE TITLE
`idf.py build` throwing many errors

### ISSUE THREAD

**Issue by akhilgupta1093** [golioth/golioth-esp-idf-sdk#71]
### ESP-IDF version

ESP-IDF v5.1-dev-1498-g2d9e75bf05

### Golioth ESP-IDF SDK Commit Hash

15de35e1134048c67b425bdfdf73a6771abdc627

### Hardware Target

ESP32S3

### What host OS are you using?

macOS Monterey

### Current Behavior

Below is the error output when I run `idf.py build` in my project, on this [branch](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/tree/esp32_golioth/software_esp32). I'm running it on this branch as is, with no changes.

A lot of the errors I'm seeing are from the golioth submodule, but I'm not sure whether this is a versioning issue, settings issue, or something else. 

[idf_error_output.txt](https://github.com/golioth/golioth-esp-idf-sdk/files/9906867/idf_error_output.txt)

### Expected Behavior

I expect to successfully build using `idf.py build`

### Steps To Reproduce

1. Clone the repository and `esp32_golioth` branch shown above
2. Run `get_idf` (`. $HOME/esp/esp-idf/export.sh`)
3. Run `idf.py build`

### Logs, console output, or any kind of debug information

```shell
The output log is attached above
```

**Comment by ncmiller** [comment]
Hi @akhilgupta1093 , thanks for reporting this. I'm able to reproduce your errors on that ESP-IDF version.

Currently, our SDK does not support anything after v4.4.2 of ESP-IDF (which is the latest official/stable release from Espressif). Generally, our SDK tracks the latest release of ESP-IDF, so when Espressif releases the first 5.x.x version, we will update the SDK to fix the errors you're encountering.

In the meantime, I'd recommend using ESP-IDF version v4.4.2 , which is the version we test our SDK against.

I'll leave this issue open until our SDK is compatible with the latest 5.x.x ESP-IDF.

**Comment by beriberikix** [comment]
Thanks for reporting! Looks like your using v5.1-dev of the ESP-IDF but the SDK is currently only supported on v4.4.1. Can you test against v4.4.1 per [the instructions](https://github.com/golioth/golioth-esp-idf-sdk#install-esp-idf) and let us know if that fixes the build issues?

We're working on supporting v5.x but since that's not ofificially released by Espressif we don't have an ETA on our end.
